language: scala

jdk: oraclejdk8

scala:
  - 2.12.8

branches:
  only:
    - master
   
script:
  - sbt assembly

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
