language: scala

jdk: oraclejdk8

scala:
  - 2.12.8
   
script:
  - sbt assembly

addons:
  ssh_known_hosts: 18.224.69.122

after_success:
 - echo "$SSH_PRIVATE_KEY_BASE64_ENCODED" | base64 --decode > $HOME/.ssh/deploy_rsa
 - chmod 0600 $HOME/.ssh/deploy_rsa
 - eval `ssh-agent`
 - ssh-add $HOME/.ssh/deploy_rsa
 - scp -o StrictHostKeyChecking=no -i $HOME/.ssh/deploy_rsa $HOME/build/velet5/ufag/target/scala-2.12/ufag-assembly-0.1.jar $USER@$HOST:/home/$USER/ufag/ufag-$(date +%Y-%m-%d-%H-%M-%S).jar

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt
