language: scala

jdk: oraclejdk8

scala:
  - 2.12.8
   
script:
  - sbt assembly
  
addons:
  ssh_known_hosts: $HOST

after_success:
 - echo "$SSH_PRIVATE_KEY" | base64 --decode > /tmp/deploy_rsa
 - eval "$(ssh-agent -s)"
 - chmod 600 /tmp/deploy_rsa
 - printf "\n\n" | ssh-add /tmp/deploy_rsa
 - scp $HOME/build/velet5/ufag/target/scala-2.12/ufag-assembly-0.1.jar $USER@$HOST:/home/$USER/ufag/ufag-$(date +%Y-%m-%d-%H-%M-%S).jar

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt
