language: scala

services:
  - docker

jdk: openjdk8

scala:
  - 2.12.8

branches:
  only:
    - master
   
script:
  - sbt docker

deploy:
  provider: script
  script: bash scripts/docker-deploy.sh
  skip_cleanup: true

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
