language: scala

jdk: oraclejdk8

scala:
  - 2.12.8

branches:
  only:
    - master
   
script:
  - sbt assembly

deploy:
  provider: script
  script: scripts/deploy.sh

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
